### ISSUE TITLE
ability to run r.js outside of a django project

### ISSUE THREAD

**Issue by sheppard** [etianen/django-require#28]
Just found this project, it looks pretty useful!  What do you think about factoring out the Django dependency in a couple places so that one could `run_optimizer()` outside of a Django project?  While I use Django pretty extensively, I have gotten in the habit of maintaining a strict modular separation between my [client](https://github.com/wq/wq.app) and [server](https://github.com/wq/wq.db) libraries, in part because there are a few projects where I can only use one or the other.

My [build process](https://github.com/wq/wq.app/blob/master/util/compilers.py) already includes a call to execute r.js via `subprocess` but I'm interested in replacing it with yours (mostly so I can get some of your `AutoEnvironment` magic).  To accomplish this without a major refactoring, I'm thinking of something like the following API:

``` python
os.environ['REQUIRE_SETTINGS'] = "app.require_settings"
from require import optimize
optimize()
```

Then `LazySettings` might get a bit lazier:

``` python
class LazySettings(object):
    @cached_property
    def config(self):
        if 'DJANGO_SETTINGS_MODULE' in os.environ:
            from django.conf import settings
            return settings
        else:
            return load_module(os.environ['REQUIRE_SETTINGS'])

    @property
    def REQUIRE_BASE_URL(self):
        return getattr(self.config, "REQUIRE_BASE_URL", "js")
# ...
```

`TemporaryCompileEnvironment` would probably need to move out of `storage`, and maybe have a non-temporary version that used whatever was in the build profile as directory paths.  `optimize()` would just be a thin convenience wrapper to initialize and run a compile environment.

What do you think?  I'm happy to submit a PR for this change, but I thought I'd run it by you first to see a.) if this feature would be useful to others and b.) if the above would be the right way to do it.

**Comment by sheppard** [comment]
Just following up on this - I've come up with a (relatively) pythonic solution for running RequireJS, based on PyMiniRacer.  I just published an alpha version to PyPI.

Have a look here:
https://github.com/wq/python-requirejs

**Comment by etianen** [comment]
Interesting! Thanks for sharing! I did not know about PyMiniRacer!
