### ISSUE TITLE
Can't set REQUIRE_BASE_URL to empty string (aka exactly STATIC_ROOT)

### ISSUE THREAD

**Issue by lsapan** [etianen/django-require#47]
When I set `REQUIRE_BASE_URL = ""`, it defaults to `"js"` because an empty string is falsey. As a workaround I tried `REQUIRE_BASE_URL = "../static"` and `REQUIRE_BASE_URL = "../static/"` but they cause some bizarre errors.

Hopefully it should just be as simple as checking for an empty string before checking for a truthy/falsey value.

**Comment by etianen** [comment]
I don’t think that django-require is creating that behaviour. You see, the setting is looked up using getattr(django_settings, "REQUIRE_BASE_URL", "js”)

I wonder if this is happening in require.js itself?

Try setting your base URL to “.” ?

**Comment by lsapan** [comment]
I had tried setting it to "." as well. That's very odd. In any case, I gave up and just decided to run r.js manually. Thanks for responding though!
