### ISSUE TITLE
I want to get build.txt output of r.js optimizer

### ISSUE THREAD

**Issue by pcompassion** [etianen/django-require#48]
I'm tyring to hash file names and append to requirejs's config.

since build.txt has the `.js` files it processed, I could use it. but TemporaryCompileEnvironment deletes the directory it seems.

I don't see a way of overriding the environment class or storage to save the build.txt.

Thanks!

**Comment by etianen** [comment]
Try setting:

REQUIRE_EXCLUDE = ()

in your settings.py. It’s default value is (“built.txt”,), to exclude that file from the final build product.

You’ll find build.txt in your STATIC_ROOT after collect static.

**Comment by pcompassion** [comment]
oh, Thanks
