### ISSUE TITLE
Error running collect static with OptimizedCachedStaticFilesStorage

### ISSUE THREAD

**Issue by dwatkinsweb** [etianen/django-require#49]
When I run collectstatic command, I get the following error

```
Post-processed 'js\main.js' as 'js/main.62646e75ef2d.js'
Post-processed 'js\test.js' as 'js/test.5ee2469fc455.js'
Post-processed 'js\test2.js' as 'js/test2.e2c752f413a8.js'
Post-processed 'cms\PIE.htc' as 'cms/PIE.a219e20e2678.htc'
Post-processed 'cms\config.rb' as 'cms/config.a49346017e25.rb'
Post-processing 'admin/css/base.css' failed!

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\dev\test_project\lib\site-packages\django\core\management\__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "c:\dev\test_project\lib\site-packages\django\core\management\__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\dev\test_project\lib\site-packages\django\core\management\base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "c:\dev\test_project\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "c:\dev\test_project\lib\site-packages\django\core\management\base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "c:\dev\test_project\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 167, in handle_noargs
    collected = self.collect()
  File "c:\dev\test_project\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 124, in collect
    raise processed
ValueError: The file 'img/nav-bg.gif' could not be found with <require.storage.OptimizedCachedStaticFilesStorage object at 0x0000000003727C88>.
```

However, when I turn off the `OptimizedCachedStaticFilesStorage` and run the following commands manually, which from what I can tell is effectively the same thing, it works just fine.

    manage.py collectstatic -c
    r.js -o customerportal/static/js/libs/require/app.build.js appDir=../../static/ baseUrl=js dir=../../static2/

**Comment by dwatkinsweb** [comment]
I just tried using `OptimizedStaticFilesStorage` instead of `OptimizedCachedStaticFilesStorage` and it seems to work. It's failing on `background: #e1e1e1 url(../img/nav-bg.gif) top left repeat-x;` which is not being replaced with background: #e1e1e1 url(../img/nav-bg.<suffix>.gif) top left repeat-x;`.

It mentions (here)[https://docs.djangoproject.com/en/1.4/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.CachedStaticFilesStorage] that it should automatically replace it, but It does not appear to be doing so properly when using `OptimizedCachedStaticFilesStorage`.

**Comment by etianen** [comment]
Are you sure that the path to that file exists? django-require doesn’t touch CSS files. That error appears to be entirely from within django’s cache static file storage base class.

Try setting your STATICFILES_STORAGE to “django.contrib.staticfiles.storage.CachedStaticFilesStorage”, and see if you still get the error.

**Comment by dwatkinsweb** [comment]
django-require does appear to be touching the css files. It has r.js run uglify2 on pretty much everything in the static directory from what I can tell.

That file does exist in every folder this process appears to create. I see it in the original folder in django, the static foder collectstatic creates, and there appears to be two tmp folders created in `c:\Users\<username>\AppData\local\Temp\`

I set STATICFILES_STORAGE to `django.contrib.staticfiles.storage.CachedStaticFilesStorage` and ran collectstatic and it works just fine. It also works when I set it to `require.storage.OptimizedStaticFilesStorage` (Not Cached).

I ran the process in debug mode using PyCharm and put a breakpoint at `C:/dev/test_project/Lib/site-packages/django/contrib/staticfiles/storage.py:90` and it appears to be looking for a file named img/nav-bg.gif instead of admin/img/nav-bg.gif (which is converted from ../img/nav-bg.gif. I haven't really been able to figure out yet exactly why it's looking for the file incorrectly. The exception is being raised from djangos CachedStaticFilesStorage, but it only seems happen when running it with OptimizedStaticFilesStorage.

**Comment by dwatkinsweb** [comment]
I just noticed that because you do `build_storage_name = build_name.replace(os.sep, "/")` at /require/storage.py:142, then do `paths[build_storage_name] = (compiled_storage, build_name)` at /require/storage.py:163 it causes every file to be added twice in windows. Once with / and once with \\ as the separator. 

I updated to `paths[build_name] = (compiled_storage, build_name)` at /require/storage.py:163 and so it saves over top of the old entry instead of creating a new entry with '/' as the separator and so far it seems to work just fine. I haven't fully verified that all the files are accurate, but at first glance it seems correct.

**Comment by dwatkinsweb** [comment]
This has been resolved by https://github.com/etianen/django-require/pull/50
