### ISSUE TITLE
Clash with django-pipeline?

### ISSUE THREAD

**Issue by karolyi** [etianen/django-require#52]
I'm using django-pipeline to compile/compress/cache bust my SASS files.

Since it uses
```python
STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'
```

in the settings, and you want it to be changed to one of your storage module. This way it either can't do its job, or your module can't do theirs with compiling the required javascript.

Any idea on how to fix this? I've been fighting with this for 4 days, It seems I'll implement my own module at the end, as I'm starting to lose it.

**Comment by karolyi** [comment]
Okay, I created a hack, but I was really over the edge. The trick is to use multiple inheritance in a separate module. You might add this to your documentation, so other desperate guys who come after me, won't have to struggle all the way like I did:

```python
"""
    This here is an utterly ugly hack to get django-pipeline and
    django-require to function together. Since both wants to override
    STATICFILES_STORAGE (thus overriding each others functionality),
    we will have to wire them together in the right order.

    So this is what happens here.
"""

from pipeline.storage import PipelineMixin
from require.storage import OptimizedFilesMixin
from django.contrib.staticfiles.storage import ManifestStaticFilesStorage


class HackStorage(
        PipelineMixin, OptimizedFilesMixin, ManifestStaticFilesStorage):
    pass
```

**Comment by etianen** [comment]
I don’t think that is is a hack. I think this is the correct use of the mixing provided by Django, django-require, and django-pipeline. Good work!

**Comment by karolyi** [comment]
Would you update your documentation to include this issue? Meanwhile I encourage the django-pipeline project too.

**Comment by etianen** [comment]
I think it’s already in the documentation: https://github.com/etianen/django-require#creating-your-own-optimizing-storage-classes

**Comment by karolyi** [comment]
You're right, my bad. I was having so many issues around the asset management at the same time, I could not simply focus on a single one like that.

Closing this, and keep up doing your great job here. :)

**Comment by etianen** [comment]
Ah, yes, the coding horror!

My typical reaction is to grumpily reimplement everything myself, taking far longer than the original 3rd party code would have taken to understand and integrate. :P
