### ISSUE TITLE
management command just to build the standalone modules

### ISSUE THREAD

**Issue by oppianmatt** [etianen/django-require#54]
Trying to build the standalone modules requires one to run collectstatic, which can be a length process since it uglifyies2 all the files again (even if not changed). That may be required behaviour since you might change an uglify2 compressor option.

But trying to build and test a standalone module makes it hard since you got to wait and run collectstatic.

Would be nice to be able to just run the standalone module builder on it's own.

**Comment by etianen** [comment]
If you’re using the django-require template tags to embed your module, then you shouldn’t need to rebuild the standalone module on each iteration.

**Comment by oppianmatt** [comment]
It's more for when I'm trying to build a profile for the first time (never done it, and the docs are sparse, guess it's relying on the r.js docs). I keep messing it up and the lengthy process is frustrating.

Also by having it a separate command would allow someone to use django to build the js libraries into one to deliver without having to do the rest of static.

But saying that I think I actually got one to build.

**Comment by oppianmatt** [comment]
More like a build/r.js question but I'm having trouble getting it to include the submodules in the final build file. 

Anyway to run just the build part on it's own? Doesn't have to be a management command (although that would be djangoey).

**Comment by etianen** [comment]
If the uglify step is taking the time, try setting

optimize: “none”

in your build profile.

**Comment by oppianmatt** [comment]
Got it all working in the end, turns out the issue I had was that `REQUIRE_STANDALONE_MODULES` needed the module name to have the js part.

But turns out I had the first part wrong, I shouldn't have had the .js part in the template tag.
