### ISSUE TITLE
Output of require_module template tag gets escaped in Django 1.9

### ISSUE THREAD

**Issue by shelldweller** [etianen/django-require#63]
Template:

```django
{% load require %}
{% require_module 'main' %}
```

In the latest version of Django this produces:

```html
&lt;script src=&quot;/path/to/require.js&quot; data-main=&quot;/path/to/main.js&quot;&gt;&lt;/script&gt;
```

**Comment by shelldweller** [comment]
See [Django 1.9 release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape) regarding this change.

**Comment by etianen** [comment]
Looks like #62 and #64 both implement this fix. #64 is currently merged, but I'mm happy to reconsider if there's a compelling reason.

If everyone is happy with the current state of affairs, let me know, and I'll push out a new release.
