### ISSUE TITLE
Best practices for using django-require in multi-page apps

### ISSUE THREAD

**Issue by hheimbuerger** [etianen/django-require#69]
I'm trying to build a multi-page app with django-require.

My goal would be to have it build an almond standalone module on collectstatic with all my 3rdparty libraries and my page modules included, but only parse/execute the parts that the specific page module refers to, using something like this in the page:

    {% require_module 'common' %}
    <script>
        require(['common'], function(common) {
            require(['app/page1']);
        });
    </script>

Now I'm getting an error in the browser, because my libraries do not depend on the page modules, so the page modules were never included in the standalone module:

> Uncaught Error: undefined missing app/page1

So I tried to include the page-specific modules in the almond build. However, if I specify `modules` in my `app.build.js`, I get an r.js error:

> Error: If the "modules" option is used, then there should be a "dir" option set and "out" should not be used since "out" is only for single file optimization output.

My next attempt was to only build the common libs and modules into the standalone module, and keep the page-specific modules separate, so using multiple `{% require_module %}` tags like this:
    
    {% require_module 'common' %}      {# this is declared in REQUIRE_STANDALONE_MODULES #}
    {% require_module 'app/page1' %}   {# this is not! #}

However, then I suddenly get both almond and require.js into my page, and I'll probably have to maintain two almost-identical `app.build.js`es. It also doesn't execute the code in the page module, but I haven't further investigated why.

Has anyone succeeded in using django-require for multi-page apps and are there any best practices how to set this best up, so it works both in production (after collectstatic) and in DEBUG mode?

**Comment by etianen** [comment]
RequireJS can become death by configuration, if you're not careful.

I'd recommend bundling everything in one big JS file, then having a single
entrypoint method that you can use to load page-specific behaviour.

Something like:

{% require_module "main" %}
<script>
    require(["main"], function(main) {
        main.page1();
    });
</script>

**Comment by hheimbuerger** [comment]
Thanks, that should work for me!
